services:
  accomplishment-tracker-api:
    build:
      context: ./accomplishment-tracker-service
      dockerfile: Dockerfile
    ports:
      - 2010:2010
    env_file:
      - ./accomplishment-tracker-service/.env
    volumes:
      - ./accomplishment-tracker-service:/usr/src/app
    networks:
      - accomplishment-tracker-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - accomplishment-tracker-network
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
  
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - accomplishment-tracker-network
    depends_on:
      - redis
    volumes:
      - redis-insight-data:/data

volumes:
  accomplishment-tracker-data:
    driver: local
  redis-data:
    driver: local
  redis-insight-data:
    driver: local

networks:
  accomplishment-tracker-network:
    driver: bridge